-- CREATE TABLE vibration_sensor
-- (DataMessageGUID varchar(50) primary key,
-- SensorID int,
-- MessageDate int,
-- State int,
-- SignalStrength int,
-- Voltage float,
-- Battery int,
-- RawData varchar(50),
-- DisplayData varchar(100),
-- PlotValue float,
-- MetNotificationRequirements char(5),
-- GatewayID int,
-- DataValues varchar(50),
-- DataTypes char(100),
-- PlotValues varchar(50),
-- PlotLabels char(50),
-- SensorName char(30),
-- Time_stamp date)


CREATE TABLE air_quality_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE air_speed_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)

CREATE TABLE co2_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE differential_pressure_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE duct_temp_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)

CREATE TABLE vibration_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE humidity_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE light_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE motion_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE quad_temp_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)


CREATE TABLE temp_sensor
(DataMessageGUID varchar(50) primary key,
SensorID int,
MessageDate int,
State int,
SignalStrength int,
Voltage float,
Battery int,
RawData varchar(50),
DisplayData varchar(100),
PlotValue float,
MetNotificationRequirements char(5),
GatewayID int,
DataValues varchar(50),
DataTypes char(100),
PlotValues varchar(50),
PlotLabels char(50),
SensorName char(30),
Time_stamp date)